
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: 2021-09-29-nbdev-notebook2script.ipynb


variable = 'This will be exported in a module'


variable2 = 'This one as well'